name = "AssignmentSolver"
uuid = "8928493c-871c-11e9-09e1-0b378afb0546"
authors = ["Brendan McVeigh <mcveigh.brendan@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
